# Generated by Django 5.0.13 on 2025-06-29 14:25

import ckeditor_uploader.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=350, null=True)),
                ('Title_EN', models.CharField(blank=True, max_length=350, null=True)),
                ('Slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Content_EN', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='AVATAR_BLOG')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='EC_about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Content1', models.TextField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Content1_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Content2', models.TextField(blank=True, null=True, verbose_name='Nội dung 2')),
                ('Content2_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung 2')),
                ('Media3', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Content3', models.TextField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Content3_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Media4', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Content4', models.TextField(blank=True, null=True, verbose_name='Nội dung 4')),
                ('Content4_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung 4')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin về chúng tôi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EC_commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Title', models.CharField(blank=True, max_length=350, null=True)),
                ('Title_EN', models.CharField(blank=True, max_length=350, null=True)),
                ('Content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('Content_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Cam kết',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EC_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang chủ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EC_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Media2', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Media3', models.FileField(blank=True, null=True, upload_to='Media_EC')),
                ('Content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('Content_EN', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang Câu chuyện',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_dsdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên phòng khám')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ')),
                ('Link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_dsdt')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Danh sách đối tác',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_lh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ')),
                ('Link_map', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link map')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin map',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Change_Website')),
                ('Phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('Text_run', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chữ chạy')),
                ('Email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang web',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Avatar', models.ImageField(blank=True, default='user_image/user_empty.png', null=True, upload_to='user_image')),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại')),
                ('OTP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Otp')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='sleekweb_us_usernam_8b077a_idx'), models.Index(fields=['email'], name='sleekweb_us_email_49565d_idx'), models.Index(fields=['Full_name'], name='sleekweb_us_Full_na_55d14c_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
