# Generated by Django 5.0.13 on 2025-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_lh',
            name='Address_EN',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ EN'),
        ),
    ]
